
name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - run: npx snowpack build
